" vim config
" Ryan Cavicchioni

set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'

if $MONO != "yes"
    set t_Co=256            " Set to 256 color mode.
    syntax on               " Enable syntax highlighting.
    set nonumber              " Enable line numbering.
else
    " makes the autocmd's work when in MONO mode.
    filetype on
endif

set nowrap              " Disable word wrap.
set tabstop=4           " Set tab to 4 characters.
set smartindent         " Enable smart indent.
set autoindent
set shiftwidth=4        " Set smartindent width to 4 characters.
set hlsearch            " Highlight search and increment search.
set incsearch
set showmatch           " Show matching brackets.
set nomodeline          " Disable modeline support.
set softtabstop=4
set showcmd             " Show partial command in status line.
set ignorecase          " Case insensitive searching.
set smartcase           " Smart case matching.
set autowrite           " Save before switching buffers.
set number
set smarttab
set listchars=tab:·\ ,eol:$
set expandtab
set backspace=indent,eol
set textwidth=80
set spell
set ruler
set laststatus=2

nnoremap <leader>s :set spell!<CR>
nnoremap <leader>n :set number!<CR>
nnoremap <leader>rn :set relativenumber!<CR>

if has("win32")
    silent execute "!mkdir " . $HOME . "\\vimfiles\\backup"
    silent execute "!mkdir " . $HOME . "\\vimfiles\\swp"
    set backupdir=~/vimfiles/backup/
    set directory=~/vimfiles/swp/
else
    silent !mkdir -p ~/.vim/{backup,swp}/
    set backupdir=~/.vim/backup/
    set directory=~/.vim/swp/
endif

au BufNewFile,BufRead *.txt set ft=text
au FileType text set tw=72 spell spelllang=en_us nonumber

au FileType mail set tw=72 spell spelllang=en_us nonumber
au FileType gitcommit set tw=72 spell spelllang=en_us nonumber
au BufNewFile,BufEnter *.phtml set tabstop=2 shiftwidth=2 softtabstop=2
au BufNewFile,BufEnter *.twig set tabstop=2 shiftwidth=2 softtabstop=2 ft=htmljinja
au FileType html set tabstop=2 shiftwidth=2 softtabstop=2
au FileType xml set tabstop=2 shiftwidth=2 softtabstop=2
au FileType ant set tabstop=2 shiftwidth=2 softtabstop=2
au FileType yaml set tabstop=2 shiftwidth=2 softtabstop=2
au FileType php set tabstop=4 shiftwidth=4 softtabstop=4
au FileType make set noexpandtab
au FileType ruby,eruby setlocal ts=2 sw=2 tw=79 et sts=2 autoindent colorcolumn=80
au FileType puppet setlocal ts=2 sw=2 tw=80 et sts=2 autoindent colorcolumn=80

" keyboard shortcuts
nmap <silent> <leader>l :set list!<CR>
nmap <silent> <leader>t :NERDTreeToggle<CR>
nmap <silent> <leader>u :GundoToggle<CR>

"call pathogen#helptags()
"call pathogen#runtime_append_all_bundles()

filetype off 

" Plugins
Plugin 'Shougo/vimproc'
Plugin 'sjl/gundo.vim.git'
Plugin 'scrooloose/nerdcommenter.git'
Plugin 'scrooloose/nerdtree.git'
Plugin 'msanders/snipmate.vim.git'
Plugin 'godlygeek/tabular.git'
Plugin 'tpope/vim-surround.git'
Plugin 'mattn/gist-vim.git'
Plugin 'tpope/vim-fugitive.git'
Plugin 'python.vim'
Plugin 'kien/ctrlp.vim.git'
Plugin 'scratch.vim'
Plugin 'bling/vim-airline'
Plugin 'tpope/vim-characterize'
Plugin 'tpope/vim-vinegar'

" Syntax
Plugin 'groenewege/vim-less.git'
Plugin 'tpope/vim-haml.git'
Plugin 'jnwhiteh/vim-golang'
Plugin 'slim-template/vim-slim.git'
Plugin 'juvenn/mustache.vim.git'
Plugin 'puppetlabs/puppet-syntax-vim.git'

" Themes
Plugin 'jnurmine/Zenburn.git'
Plugin 'nanotech/jellybeans.vim.git'
Plugin 'guns/jellyx.vim.git'
Plugin 'strange/strange.vim.git'
Plugin 'veloce/vim-aldmeris.git'
Plugin 'altercation/vim-colors-solarized.git'
Plugin 'Lokaltog/vim-distinguished.git'
Plugin 'nelstrom/vim-mac-classic-theme.git'
Plugin 'atonse/vydark.git'
Plugin 'vim-scripts/vylight.git'
Plugin 'tpope/vim-vividchalk.git'
Plugin 'ciaranm/inkpot.git'
Plugin 'jpo/vim-railscasts-theme.git'
Plugin 'oguzbilgic/sexy-railscasts-theme.git'
Plugin 'mrkn/mrkn256.vim.git'
Plugin 'bcat/abbott.vim.git'
Plugin 'twilight256.vim'
Plugin 'vilight.vim'
Plugin 'dasch/vim-mocha.git'
Plugin 'dasch/satellite.git'
Plugin 'djjcast/mirodark.git'
Plugin 'molok/vim-vombato-colorscheme.git'
"Plugin 'jelera/vim-gummybears-colorscheme.git'
Plugin 'vim-scripts/Gummybears'
Plugin 'sjl/badwolf.git'
Plugin 'shawncplus/skittles_berry.git'
Plugin 'Skittles-Dark'
Plugin 'tortex'
Plugin 'mayansmoke'
Plugin 'w0ng/vim-hybrid.git'
Plugin 'blackgate/tropikos-vim-theme.git'
Plugin 'zaki/zazen.git'
Plugin 'jonathanfilip/vim-lucius.git'
Plugin 'chriskempson/vim-tomorrow-theme.git'
Plugin 'tangphillip/SunburstVIM.git'
Plugin 'nelstrom/vim-blackboard.git'
Plugin 'tomasr/molokai.git'
Plugin 'zeis/vim-kolor.git'
Plugin 'morhetz/gruvbox.git'
Plugin 'trapd00r/neverland-vim-theme.git'
Plugin 'chriskempson/base16-vim.git'
Plugin 'changyuheng/color-scheme-holokai-of-vim.git'
Plugin 'noahfrederick/Hemisu.git'
Plugin 'sk1418/last256.git'
Plugin 'toupeira/vim-desertink.git'
Plugin 'junegunn/seoul256.vim.git'
Plugin 'lsdr/monokai'
"Plugin 'daylerees/colour-schemes', { "rtp": "vim" }
Plugin 'Pychimp/vim-luna'
Plugin 'Pychimp/vim-sol'
Plugin 'vim-scripts/wombat256.vim'
Plugin 'vim-scripts/Wombat'
Plugin 'hukl/Smyck-Color-Scheme'
Plugin 'tpope/vim-commentary'
Plugin 'itchyny/landscape.vim'
Plugin 'reedes/vim-colors-pencil'
Plugin 'Shougo/unite.vim'
Plugin 'whatyouhide/vim-gotham'

call vundle#end()
filetype plugin indent on

colorscheme last256

" Force hash comments to retain their indentation level.
inoremap # X#

" Configure airline
let g:airline#extensions#tabline#enabled = 1
let g:airline_left_sep=''
let g:airline_right_sep=''

" Configure unite
nnoremap <leader>f :<C-u>Unite -start-insert file<CR>
nnoremap <leader>b :<C-u>Unite -start-insert buffer<CR>

" If it exists, include user's local vim config
if filereadable(expand("~/.vimrc.local"))
    source ~/.vimrc.local
endif
